### ISSUE TITLE
Weight formatting/precision

### ISSUE THREAD

**Issue by helgatheviking** [kathyisawesome/wc-mnm-weight#7]
How to handle weights like 12.777777777777777777777777777777?

Also, possible precision issue reported in https://secure.helpscout.net/conversation/1503068278/2343?folderId=3928219

>. It's slightly odd because the product weight is actually set to "0.3" (kg). When I add 3 of these to the basket the expected weight is 0.9 (kg). However, the weight displayed is 0.8999999999999999.

**Comment by Sam-Xronn** [comment]
For anyone else that stumbles across this, here is my temporary fix. 

**Note*** Future plugin updates will potentially reverse this change!


Inside `wc-add-to-cart-mnm-weight-validation.js` replace the following line; 
`container.$mnm_cart.data( 'total_weight', total_weight );` 
With;
`container.$mnm_cart.data( 'total_weight', total_weight.toFixed(2) );`

You'll need to compile this js file into the minified file.
